FROM python:3.9

WORKDIR /api

COPY etc/requirements.api.txt /api/requirements.api.txt
COPY src/api/ /api/src/api/

RUN pip install --no-cache-dir --upgrade -r /api/requirements.api.txt

VOLUME [ "/mlruns" ]

EXPOSE 8080

ENTRYPOINT [ "uvicorn", "src.api.serve_model:app", "--host", "0.0.0.0", "--port", "8080" ]