version: '3.7'

services:
  api_model:
    build:
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - MLFLOW_BACKEND_STORE_URI=/mlruns
    volumes:
      - /mlruns:/api/mlruns