data:
  raw:
    path: data/imdb_data.csv
  processed:
    path: data/imdb_data_processed.csv

model:
  path: output/xgb.json
  path_param: etc/model_param.json

mlflow:
  backend_store_path: file:///home/mlflow-backend-store