name: imdb
channels:
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  - pip:
    - dash==2.16.1
    - dash-bootstrap-components==1.5.0
    - dvc==3.48.2
    - fastapi==0.110.0
    - jupyterlab==4.1.3
    - matplotlib==3.8.3
    - mlflow==2.11.1
    - pandas==1.5.3
    - plotly==5.19.0
    - scikit-learn==1.4.1
    - scipy==1.12.0
    - shap==0.44.1
    - uvicorn==0.27.1
    - xgboost==2.0.3