name: imdb
channels:
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  - pip:
    - dash==2.16.1
    - dash-bootstrap-components==1.5.0
    - dvc==3.48.2
    - jupyterlab==4.1.3
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - -r requirements.api.txt