name: imdb
channels:
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  - pip:
    - jupyterlab==4.1.3
    - matplotlib==3.8.3
    - pandas==1.5.3
    - plotly==5.19.0
    - scikit-learn==1.4.1
    - scipy==1.12.0
    - shap==0.44.1
    - xgboost==2.0.3