apiVersion: apps/v1
kind: Deployment
metadata:
  name: imdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imdb-app
  template:
    metadata:
      labels:
        app: imdb-app
    spec:
      containers:
      - name: imdb-app
        image: imdb-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
      #   volumeMounts:
      #   - name: mlflow-backend-store
      #     mountPath: /data
      # volumes:
      # - name: mlflow-backend-store
      #   hostPath:
      #     path: /home/mlflow-backend-store
      #     type: Directory
